// <auto-generated />
using System;
using Atlas.Data.Global;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Data.Global.Migrations.Migrations
{
    [DbContext(typeof(AtlasGlobalDbContext))]
    partial class AtlasGlobalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Atlas.Core.Entities.Global.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CancellationReason"), "utf8mb4");

                    b.Property<string>("CancellationRequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CancellationRequestedBy"), "utf8mb4");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DeduplicationKey"), "utf8mb4");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JobName"), "utf8mb4");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JobType"), "utf8mb4");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastError"), "utf8mb4");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LockedBy"), "utf8mb4");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Payload"), "utf8mb4");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Queue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("default");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Queue"), "utf8mb4");

                    b.Property<string>("Result")
                        .HasMaxLength(1000000)
                        .HasColumnType("mediumtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Result"), "utf8mb4");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("JobType")
                        .HasDatabaseName("IX_BackgroundJobs_JobType");

                    b.HasIndex("Queue")
                        .HasDatabaseName("IX_BackgroundJobs_Queue");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_BackgroundJobs_Tenant_CreatedAt");

                    b.HasIndex("TenantId", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_BackgroundJobs_Tenant_DeduplicationKey");

                    b.HasIndex("Queue", "Status", "LockedAtUtc")
                        .HasDatabaseName("IX_BackgroundJobs_RunningLocks");

                    b.HasIndex("Status", "CancellationRequestedAt")
                        .HasDatabaseName("IX_BackgroundJobs_CancellationRequested");

                    b.HasIndex("Queue", "Status", "AvailableAtUtc", "NextAttemptAtUtc", "Priority")
                        .HasDatabaseName("IX_BackgroundJobs_DispatchDue");

                    b.ToTable("BackgroundJobs", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.BackgroundWorkerHeartbeat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CurrentJobId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentJobType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CurrentJobType"), "utf8mb4");

                    b.Property<string>("CurrentQueue")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CurrentQueue"), "utf8mb4");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HostName"), "utf8mb4");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OneTimeJobWorkerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("QueuesJson")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("QueuesJson"), "utf8mb4");

                    b.Property<bool>("RecurringTaskRunnerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RuntimeMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RuntimeMode"), "utf8mb4");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("WorkerId"), "utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CurrentJobId")
                        .HasDatabaseName("IX_BackgroundWorkerHeartbeats_CurrentJobId");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("IX_BackgroundWorkerHeartbeats_LastSeenAtUtc");

                    b.HasIndex("ProcessId");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("UX_BackgroundWorkerHeartbeats_WorkerId");

                    b.HasIndex("RuntimeMode", "LastSeenAtUtc")
                        .HasDatabaseName("IX_BackgroundWorkerHeartbeats_Runtime_LastSeen");

                    b.ToTable("BackgroundWorkerHeartbeats", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.Capability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Category"), "utf8mb4");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceModule"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Capabilities_Code");

                    b.HasIndex("Category", "IsEnabled")
                        .HasDatabaseName("IX_Capabilities_Category_Enabled");

                    b.ToTable("Capabilities", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.DatabaseInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库连接串（可选，优先级高于ServerConfig）");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ConnectionString"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库名称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DbName"), "utf8mb4");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库类型：SqlServer, MySQL, PostgreSQL");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DbType"), "utf8mb4");

                    b.Property<string>("MasterServerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("主数据库Server编码");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MasterServerCode"), "utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("实例名称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("所属区域：华东、华北、华南等");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Region"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库版本");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Version"), "utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("DbType")
                        .HasDatabaseName("IX_DatabaseInstances_DbType");

                    b.HasIndex("MasterServerCode")
                        .HasDatabaseName("IX_DatabaseInstances_MasterServerCode");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_DatabaseInstances_Region");

                    b.ToTable("DatabaseInstances", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.DatabaseMasterServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("服务器编码（唯一标识）");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("服务器昵称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NickName"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_DatabaseMasterServers_Code");

                    b.ToTable("DatabaseMasterServers", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.DatabaseReadonlyServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("只读服务器编码（唯一标识）");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否公开给周边服务访问");

                    b.Property<bool>("IsReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否是报表只读库");

                    b.Property<string>("MasterServerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("所属主数据库Server编码");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MasterServerCode"), "utf8mb4");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("只读服务器昵称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NickName"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_DatabaseReadonlyServers_Code");

                    b.HasIndex("MasterServerCode")
                        .HasDatabaseName("IX_DatabaseReadonlyServers_MasterServerCode");

                    b.HasIndex("IsPublic", "MasterServerCode")
                        .HasDatabaseName("IX_DatabaseReadonlyServers_IsPublic_MasterServerCode");

                    b.HasIndex("IsReport", "MasterServerCode")
                        .HasDatabaseName("IX_DatabaseReadonlyServers_IsReport_MasterServerCode");

                    b.ToTable("DatabaseReadonlyServers", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.DatabaseServerConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ConnString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库连接串");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ConnString"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("数据库类型：SqlServer, MySQL, PostgreSQL");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DbType"), "utf8mb4");

                    b.Property<string>("NetworkEnvCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("default")
                        .HasComment("网络环境编码：default, classic, vpc");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NetworkEnvCode"), "utf8mb4");

                    b.Property<string>("ServerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("服务器编码（关联MasterServer或ReadonlyServer）");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ServerCode"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("NetworkEnvCode")
                        .HasDatabaseName("IX_DatabaseServerConfigs_NetworkEnvCode");

                    b.HasIndex("ServerCode")
                        .HasDatabaseName("IX_DatabaseServerConfigs_ServerCode");

                    b.HasIndex("ServerCode", "NetworkEnvCode", "DbType")
                        .IsUnique()
                        .HasDatabaseName("UX_DatabaseServerConfigs_ServerCode_NetworkEnvCode_DbType");

                    b.ToTable("DatabaseServerConfigs", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.ExportJob", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BackgroundJobId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContentType"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExportTaskType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ExportTaskType"), "utf8mb4");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FileName"), "utf8mb4");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Format"), "utf8mb4");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastError"), "utf8mb4");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PermissionCode"), "utf8mb4");

                    b.Property<long>("ProcessedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("QueryHash"), "utf8mb4");

                    b.Property<string>("QueryJson")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("QueryJson"), "utf8mb4");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ResourceCode"), "utf8mb4");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Sha256"), "utf8mb4");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StorageKey"), "utf8mb4");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StorageProvider"), "utf8mb4");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalRows")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundJobId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExportJobs_BackgroundJobId");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_ExportJobs_ExpiresAtUtc");

                    b.HasIndex("ExportTaskType")
                        .HasDatabaseName("IX_ExportJobs_ExportTaskType");

                    b.HasIndex("ResourceCode")
                        .HasDatabaseName("IX_ExportJobs_ResourceCode");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_ExportJobs_TenantId_Status");

                    b.HasIndex("TenantId", "UserId", "RequestedAtUtc")
                        .HasDatabaseName("IX_ExportJobs_TenantId_UserId_RequestedAtUtc");

                    b.ToTable("ExportJobs", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.FeaturePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceModule"), "utf8mb4");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_FeaturePackages_Code");

                    b.HasIndex("Type", "IsEnabled")
                        .HasDatabaseName("IX_FeaturePackages_Type_Enabled");

                    b.ToTable("FeaturePackages", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Icon"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ParentCode"), "utf8mb4");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Route"), "utf8mb4");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceModule"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VisibleWhenJson")
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("VisibleWhenJson"), "utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_MenuItems_Code");

                    b.HasIndex("ParentCode", "SortOrder")
                        .HasDatabaseName("IX_MenuItems_Parent_Sort");

                    b.ToTable("MenuItems", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.PackageCapability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CapabilityCode"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LimitJson")
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LimitJson"), "utf8mb4");

                    b.Property<string>("OptionJson")
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OptionJson"), "utf8mb4");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PackageCode"), "utf8mb4");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceModule"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityCode")
                        .HasDatabaseName("IX_PackageCapabilities_Capability");

                    b.HasIndex("PackageCode", "CapabilityCode")
                        .IsUnique()
                        .HasDatabaseName("UX_PackageCapabilities_Package_Capability");

                    b.ToTable("PackageCapabilities", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)")
                        .HasComment("公司地址");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Address"), "utf8mb4");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)")
                        .HasComment("品牌名称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("BrandName"), "utf8mb4");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("连锁类型：Single, Chain, Franchise");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("租户类别：试用、Mobile等");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Category"), "utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("城市");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("City"), "utf8mb4");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("联系人邮箱");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactEmail"), "utf8mb4");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("联系人姓名");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactName"), "utf8mb4");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("联系人手机号");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactPhoneNumber"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("创建人ID");

                    b.Property<long>("DatabaseInstanceId")
                        .HasColumnType("bigint")
                        .HasComment("关联的数据库实例ID");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasComment("删除人ID");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)")
                        .HasComment("公司代码（租户唯一标识，用于登录）");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Domain"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否已删除（软删除）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)")
                        .HasComment("公司名称");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<int>("OfficeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("诊所/门店数量");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("公司电话");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PhoneNumber"), "utf8mb4");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasComment("省份");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Province"), "utf8mb4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("租户状态：Active, Inactive, Suspended");

                    b.Property<string>("TenantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("租户类型：Enterprise, Individual");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("更新人ID");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Tenants_City");

                    b.HasIndex("DatabaseInstanceId")
                        .HasDatabaseName("IX_Tenants_DatabaseInstanceId");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenants_Domain");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tenants_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tenants_Status");

                    b.HasIndex("Status", "TenantType")
                        .HasDatabaseName("IX_Tenants_Status_TenantType");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.TenantEntitlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CapabilityCode")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CapabilityCode"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionOverrideJson")
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OptionOverrideJson"), "utf8mb4");

                    b.Property<string>("PackageCode")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PackageCode"), "utf8mb4");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("SubjectType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CapabilityCode")
                        .HasDatabaseName("IX_TenantEntitlements_Capability");

                    b.HasIndex("TenantId", "PackageCode")
                        .HasDatabaseName("IX_TenantEntitlements_Package");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId", "Status")
                        .HasDatabaseName("IX_TenantEntitlements_Subject_Status");

                    b.ToTable("TenantEntitlements", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.TenantSchemaMigrationState", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CurrentVersion"), "utf8mb4");

                    b.Property<DateTime?>("LastAttemptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("text");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastError"), "utf8mb4");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TargetVersion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TargetVersion"), "utf8mb4");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantSchemaMigrationStates_TenantId");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("IX_TenantSchemaMigrationStates_Status_UpdatedAtUtc");

                    b.ToTable("TenantSchemaMigrationStates", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("Delivered");

                    b.HasIndex("LockId");

                    b.HasIndex("MessageId");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Body"), "utf8mb4");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContentType"), "utf8mb4");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Headers"), "utf8mb4");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MessageType"), "utf8mb4");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Properties"), "utf8mb4");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("InboxConsumerId");

                    b.HasIndex("InboxMessageId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("MessageId");

                    b.HasIndex("OutboxId");

                    b.HasIndex("RequestId");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.HasIndex("LockId");

                    b.HasIndex("OutboxId");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.Tenant", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Global.DatabaseInstance", "DatabaseInstance")
                        .WithMany("Tenants")
                        .HasForeignKey("DatabaseInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseInstance");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Global.DatabaseInstance", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
