// <auto-generated />
using System;
using Atlas.Data.Tenant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Data.Tenant.Migrations.Migrations
{
    [DbContext(typeof(AtlasTenantDbContext))]
    [Migration("20251117030718_v0.0.3-auto-id")]
    partial class v003autoid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.CashierRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_CashierRecords_IsDeleted");

                    b.HasIndex("OrderId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_CashierRecords_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("IX_CashierRecords_TenantId_OrderId");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_CashierRecords_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "PaidAt")
                        .HasDatabaseName("IX_CashierRecords_TenantId_StoreId_PaidAt");

                    b.ToTable("CashierRecords", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SafetyStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Inventorys_IsDeleted");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Inventorys_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Inventorys_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventories_TenantId_StoreId_ProductId");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Members_IsDeleted");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Members_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "Phone")
                        .HasDatabaseName("IX_Members_TenantId_Phone");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Members_TenantId_StoreId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Orders_IsDeleted");

                    b.HasIndex("MemberId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Orders_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("IX_Orders_TenantId_MemberId");

                    b.HasIndex("TenantId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_TenantId_OrderNo");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Orders_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "Status")
                        .HasDatabaseName("IX_Orders_TenantId_StoreId_Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsCustomized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SourceStoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Products_IsDeleted");

                    b.HasIndex("SourceStoreId")
                        .HasDatabaseName("IX_Products_SourceStoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Products_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Products_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "IsCustomized")
                        .HasDatabaseName("IX_Products_TenantId_StoreId_IsCustomized");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long?>("SourceStoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Promotions_IsDeleted");

                    b.HasIndex("SourceStoreId")
                        .HasDatabaseName("IX_Promotions_SourceStoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Promotions_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Promotions_TenantId_StoreId");

                    b.HasIndex("TenantId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Promotions_TenantId_StartTime_EndTime");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ParentStoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Stores_IsDeleted");

                    b.HasIndex("ParentStoreId")
                        .HasDatabaseName("IX_Stores_ParentStoreId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Stores_TenantId");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_Stores_TenantId_IsActive");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("IX_Stores_TenantId_Type");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Store", b =>
                {
                    b.HasOne("Atlas.Models.Tenant.Entities.Store", "ParentStore")
                        .WithMany("ChildStores")
                        .HasForeignKey("ParentStoreId");

                    b.Navigation("ParentStore");
                });

            modelBuilder.Entity("Atlas.Models.Tenant.Entities.Store", b =>
                {
                    b.Navigation("ChildStores");
                });
#pragma warning restore 612, 618
        }
    }
}
