// <auto-generated />
using System;
using Atlas.Data.Tenant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Data.Tenant.Migrations.Migrations
{
    [DbContext(typeof(AtlasTenantDbContext))]
    [Migration("20260517021013_v0.1.4-tenant-isolation-hardening")]
    partial class v014tenantisolationhardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.CashierRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_CashierRecords_IsDeleted");

                    b.HasIndex("OrderId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_CashierRecords_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("IX_CashierRecords_TenantId_OrderId");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_CashierRecords_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "PaidAt")
                        .HasDatabaseName("IX_CashierRecords_TenantId_StoreId_PaidAt");

                    b.ToTable("CashierRecords", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SafetyStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Inventorys_IsDeleted");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Inventorys_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Inventorys_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventories_TenantId_StoreId_ProductId");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Member", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MemberName"), "utf8mb4");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Phone"), "utf8mb4");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Members_IsDeleted");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Members_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "Phone")
                        .HasDatabaseName("IX_Members_TenantId_Phone");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Members_TenantId_StoreId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Changes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Changes"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb4");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ErrorMessage"), "utf8mb4");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("IpAddress"), "utf8mb4");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Module"), "utf8mb4");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OperationType"), "utf8mb4");

                    b.Property<string>("SessionId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionId"), "utf8mb4");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_BusinessOperationLogs_CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_BusinessOperationLogs_SessionId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_BusinessOperationLogs_UserId");

                    b.HasIndex("Module", "EntityId")
                        .HasDatabaseName("IX_BusinessOperationLogs_Module_EntityId");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_BusinessOperationLogs_TenantId_UserId");

                    b.HasIndex("Module", "OperationType", "CreatedAt")
                        .HasDatabaseName("IX_BusinessOperationLogs_Module_Type_CreatedAt");

                    b.ToTable("OperationLogs", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OrderNo"), "utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Orders_IsDeleted");

                    b.HasIndex("MemberId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Orders_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("IX_Orders_TenantId_MemberId");

                    b.HasIndex("TenantId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_TenantId_OrderNo");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Orders_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "Status")
                        .HasDatabaseName("IX_Orders_TenantId_StoreId_Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Product", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb4");

                    b.Property<bool>("IsCustomized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SourceStoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Products_IsDeleted");

                    b.HasIndex("SourceStoreId")
                        .HasDatabaseName("IX_Products_SourceStoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Products_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Products_TenantId_StoreId");

                    b.HasIndex("TenantId", "StoreId", "IsCustomized")
                        .HasDatabaseName("IX_Products_TenantId_StoreId_IsCustomized");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long?>("SourceStoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Title"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Promotions_IsDeleted");

                    b.HasIndex("SourceStoreId")
                        .HasDatabaseName("IX_Promotions_SourceStoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_Promotions_TenantId_IsDeleted");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("IX_Promotions_TenantId_StoreId");

                    b.HasIndex("TenantId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Promotions_TenantId_StartTime_EndTime");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Store", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Address"), "utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("City"), "utf8mb4");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Code"), "utf8mb4");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactPerson"), "utf8mb4");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactPhone"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("District"), "utf8mb4");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<long?>("ParentStoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Province"), "utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Stores_IsDeleted");

                    b.HasIndex("ParentStoreId")
                        .HasDatabaseName("IX_Stores_ParentStoreId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Stores_TenantId");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_Stores_TenantId_IsActive");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("IX_Stores_TenantId_Type");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.TenantInboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ConsumerName"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivedAtUtc")
                        .HasDatabaseName("IX_TenantInboxMessages_Tenant_ReceivedAt");

                    b.HasIndex("TenantId", "MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantInboxMessages_Tenant_Message_Consumer");

                    b.ToTable("TenantInboxMessages", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.TenantOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventName"), "utf8mb4");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastError"), "utf8mb4");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MessageType"), "utf8mb4");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Payload"), "utf8mb4");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProcessingAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProcessingBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ProcessingBy"), "utf8mb4");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantOutboxMessages_Tenant_EventId");

                    b.HasIndex("TenantId", "ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasDatabaseName("IX_TenantOutboxMessages_Tenant_ProcessDue");

                    b.HasIndex("TenantId", "ProcessingAtUtc", "ProcessedAtUtc")
                        .HasDatabaseName("IX_TenantOutboxMessages_Tenant_Processing");

                    b.ToTable("TenantOutboxMessages", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Avatar"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultStoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "utf8mb4");

                    b.Property<string>("EmployeeNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EmployeeNo"), "utf8mb4");

                    b.Property<string>("ExtendedData")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ExtendedData"), "utf8mb4");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastLoginIp"), "utf8mb4");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoginFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NickName"), "utf8mb4");

                    b.Property<DateTime?>("PasswordExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PasswordHash"), "utf8mb4");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Phone"), "utf8mb4");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Position"), "utf8mb4");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RealName"), "utf8mb4");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Remark"), "utf8mb4");

                    b.Property<string>("RoleIds")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RoleIds"), "utf8mb4");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserName"), "utf8mb4");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DefaultStoreId")
                        .HasDatabaseName("IX_Users_DefaultStoreId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Users_IsDeleted");

                    b.HasIndex("TenantId");

                    b.HasIndex("Id", "TokenVersion")
                        .HasDatabaseName("IX_Users_Id_TokenVersion");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_Users_TenantId_Email");

                    b.HasIndex("TenantId", "EmployeeNo")
                        .HasDatabaseName("IX_Users_TenantId_EmployeeNo");

                    b.HasIndex("TenantId", "Phone")
                        .HasDatabaseName("IX_Users_TenantId_Phone");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("IX_Users_TenantId_Type");

                    b.HasIndex("TenantId", "UserName")
                        .HasDatabaseName("IX_Users_TenantId_UserName");

                    b.HasIndex("TenantId", "Status", "IsDeleted")
                        .HasDatabaseName("IX_Users_TenantId_Status_IsDeleted");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserLoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Browser"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DeviceType"), "utf8mb4");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FailureReason"), "utf8mb4");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("IpAddress"), "utf8mb4");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoginMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("Password");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LoginMethod"), "utf8mb4");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogoutType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LogoutType"), "utf8mb4");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OperatingSystem"), "utf8mb4");

                    b.Property<string>("SessionId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SessionId"), "utf8mb4");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserAgent"), "utf8mb4");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserLoginLogs_CreatedAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_UserLoginLogs_SessionId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserLoginLogs_UserId");

                    b.HasIndex("IpAddress", "CreatedAt")
                        .HasDatabaseName("IX_UserLoginLogs_IpAddress_CreatedAt");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_UserLoginLogs_TenantId_UserId");

                    b.HasIndex("UserId", "IsSuccess", "CreatedAt")
                        .HasDatabaseName("IX_UserLoginLogs_UserId_IsSuccess_CreatedAt");

                    b.ToTable("UserLoginLogs", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GrantedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_UserRoles_TenantId_UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRoles_UserId_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Permission")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(256)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Permission"), "utf8mb4");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_UserStores_StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserStores_UserId");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_UserStores_TenantId_UserId");

                    b.HasIndex("UserId", "IsPrimary")
                        .HasDatabaseName("IX_UserStores_UserId_IsPrimary");

                    b.HasIndex("UserId", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserStores_UserId_StoreId");

                    b.ToTable("UserStores", (string)null);
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Store", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Tenant.Store", "ParentStore")
                        .WithMany("ChildStores")
                        .HasForeignKey("ParentStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentStore");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.User", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Tenant.Store", "DefaultStore")
                        .WithMany()
                        .HasForeignKey("DefaultStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultStore");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserLoginLog", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Tenant.User", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserRole", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Tenant.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.UserStore", b =>
                {
                    b.HasOne("Atlas.Core.Entities.Tenant.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Core.Entities.Tenant.User", "User")
                        .WithMany("UserStores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.Store", b =>
                {
                    b.Navigation("ChildStores");
                });

            modelBuilder.Entity("Atlas.Core.Entities.Tenant.User", b =>
                {
                    b.Navigation("LoginLogs");

                    b.Navigation("UserRoles");

                    b.Navigation("UserStores");
                });
#pragma warning restore 612, 618
        }
    }
}
